"use client";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
interface Member {id:string;name:string|null;email:string;emailVerified:string|null;accessStatus:"PENDING"|"APPROVED"|"REJECTED";role:string;}
export default function AdminMembersTab(){
 const [members,setMembers]=useState<Member[]>([]);const [error,setError]=useState("");const [loading,setLoading]=useState(true);const [busy,setBusy]=useState<string|null>(null);
 async function load(){try{const res=await fetch("/api/admin/members");if(!res.ok)throw new Error("Could not load members.");setMembers(await res.json());}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 async function review(id:string,accessStatus:string){setBusy(id);setError("");try{const res=await fetch(`/api/admin/members/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({accessStatus})});const data=await res.json();if(!res.ok)throw new Error(data.error);await load();}catch(e){setError((e as Error).message);}finally{setBusy(null);}}
 return <section className="member-management"><div className="section-line"><h2>Member access</h2><span>{members.filter(m=>m.accessStatus==="PENDING").length} REQUESTS TO REVIEW</span></div><p className="text-sm text-slate-500 mb-6">You control who can sign in. Approvals are separate from profile updates. Revoking access also invalidates existing sessions.</p>{error&&<p role="alert" className="form-error mb-4">{error}</p>}{loading?<p>Loading members…</p>:members.length===0?<p className="text-sm text-slate-500">No access requests yet.</p>:<div className="space-y-3">{members.map(m=><div key={m.id} className="member-access-row"><div><strong>{m.name ?? m.email}</strong><p>{m.email}</p><small>{m.emailVerified?"Email verified":"Email verification pending"}</small></div><span className={`access-status status-${m.accessStatus.toLowerCase()}`}>{m.role==="ADMIN"?"Administrator":m.accessStatus.toLowerCase()}</span>{m.role!=="ADMIN"&&<div className="member-access-actions">{m.accessStatus!=="APPROVED"&&<Button size="sm" disabled={busy===m.id} onClick={()=>review(m.id,"APPROVED")}>Approve access</Button>}{m.accessStatus!=="REJECTED"&&<Button size="sm" variant="outline" disabled={busy===m.id} onClick={()=>review(m.id,"REJECTED")}>{m.accessStatus==="APPROVED"?"Revoke access":"Reject request"}</Button>}</div>}</div>)}</div>}</section>;
}
